const questionAnswer = [
  { "answer": "Elephant", "hint": "Largest land animal." },
  { "answer": "Computer", "hint": "Device for processing data." },
  { "answer": "Butterfly", "hint": "Insect with colorful wings." },
  { "answer": "Sunshine", "hint": "Bright light from the sky." },
  { "answer": "Mountain", "hint": "Tall landform with peaks." },
  { "answer": "Rainbow", "hint": "Colorful arch in the sky." },
  { "answer": "Adventure", "hint": "Exciting and daring experience." },
  { "answer": "Chocolate", "hint": "Sweet treat made from cacao." },
  { "answer": "Universe", "hint": "All of space, time, matter, and energy." },
  { "answer": "Symphony", "hint": "Musical composition for orchestra." },
  { "answer": "Gardening", "hint": "Cultivating plants in a garden." },
  { "answer": "Friendship", "hint": "Close and supportive relationship." },
  { "answer": "Waterfall", "hint": "Flowing water descending from a height." },
  { "answer": "Mystery", "hint": "Something that is difficult to understand." },
  { "answer": "Tornado", "hint": "Violently rotating column of air." },
  { "answer": "Fireworks", "hint": "Explosive display of colors in the sky." },
  { "answer": "Jazz", "hint": "Genre of music with improvisation." },
  { "answer": "Universe", "hint": "All of space, time, matter, and energy." },
  { "answer": "Backpack", "hint": "Bag carried on the back." },
  { "answer": "Parachute", "hint": "Device for safely landing from heights." },
  { "answer": "Ecosystem", "hint": "Biological community and its environment." },
  { "answer": "Innovation", "hint": "Introduction of something new." },
  { "answer": "Symphony", "hint": "Musical composition for orchestra." },
  { "answer": "Sailing", "hint": "Traveling on water using sails." },
  { "answer": "Champion", "hint": "Winner of a competition." },
  { "answer": "Adventure", "hint": "Exciting and daring experience." },
  { "answer": "Telescope", "hint": "Optical instrument for distant objects." },
  { "answer": "Butterfly", "hint": "Insect with colorful wings." },
  { "answer": "Moonlight", "hint": "Light from the moon." },
  { "answer": "Chocolate", "hint": "Sweet treat made from cacao." },
  { "answer": "Elephant", "hint": "Largest land animal." },
  { "answer": "Mountain", "hint": "Tall landform with peaks." },
  { "answer": "Waterfall", "hint": "Flowing water descending from a height." },
  { "answer": "Sunshine", "hint": "Bright light from the sky." },
  { "answer": "Puzzle", "hint": "Game or problem that tests intelligence." },
  { "answer": "Fireworks", "hint": "Explosive display of colors in the sky." },
  { "answer": "Symphony", "hint": "Musical composition for orchestra." },
  { "answer": "Friendship", "hint": "Close and supportive relationship." },
  { "answer": "Gardening", "hint": "Cultivating plants in a garden." },
  { "answer": "Innovation", "hint": "Introduction of something new." },
  { "answer": "Sailing", "hint": "Traveling on water using sails." },
  { "answer": "Champion", "hint": "Winner of a competition." },
  { "answer": "Parachute", "hint": "Device for safely landing from heights." },
  { "answer": "Tornado", "hint": "Violently rotating column of air." },
  { "answer": "Ecosystem", "hint": "Biological community and its environment." },
  { "answer": "Jazz", "hint": "Genre of music with improvisation." },
  { "answer": "Universe", "hint": "All of space, time, matter, and energy." },
  { "answer": "Backpack", "hint": "Bag carried on the back." },
  { "answer": "Telescope", "hint": "Optical instrument for distant objects." },
  { "answer": "Mystery", "hint": "Something that is difficult to understand." }
]

export default questionAnswer;
